using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Xml;
using System.Xml.Linq;

namespace PyExcel.State;

/// <summary>
/// Pure-XML round-trip for the user-editable slice of
/// <see cref="WorkbookState"/>. Used by the Phase-3
/// <c>WorkbookStatePersister</c> (Windows-only, COM-bound) to save into
/// and load out of a workbook's <c>CustomXMLPart</c> collection, but the
/// codec itself has no COM dependency so it builds and tests on Linux.
///
/// <para>The XML schema is intentionally hand-rolled, human-readable, and
/// versioned. The root element carries
/// <c>xmlns="urn:pyexcel:state:1"</c> so the COM-side persister can
/// locate the part among any other CustomXMLParts the workbook owns.
/// Bumping the schema means bumping the namespace.</para>
///
/// <para>What's persisted: the user-input fields
/// (<see cref="WorkbookState.Enabled"/>, <see cref="WorkbookState.SelectedScript"/>,
/// <see cref="WorkbookState.PyInput"/>, <see cref="WorkbookState.PyOutput"/>,
/// <see cref="WorkbookState.SelectedActionName"/>, and the full
/// <see cref="WorkbookState.Actions"/> list).
/// What's NOT persisted: <see cref="WorkbookState.WorkbookKey"/> (it's
/// the lookup key, not data),
/// <see cref="WorkbookState.CurrentSheet"/> (transient — derived from
/// <c>SheetActivate</c>), <see cref="WorkbookState.AvailableScripts"/>
/// (regenerated by <see cref="ScriptDirectoryWatcher"/> on workbook
/// open).</para>
/// </summary>
public static class WorkbookStateCodec
{
    /// <summary>Current schema version. Bump when the on-disk format
    /// changes in a non-backwards-compatible way.</summary>
    public const string SchemaVersion = "1";

    /// <summary>XML namespace embedded in the root element so the COM
    /// persister can find the PyExcel part among other custom parts.
    /// Reads accept only this exact namespace — see
    /// <see cref="Deserialize"/>.</summary>
    public const string XmlNamespace = "urn:pyexcel:state:1";

    private static readonly XNamespace Ns = XmlNamespace;

    /// <summary>Serialize the user-editable slice of
    /// <paramref name="state"/> into an XML document the persister can
    /// store in a <c>CustomXMLPart</c>.</summary>
    public static XDocument Serialize(WorkbookState state)
    {
        if (state is null) throw new ArgumentNullException(nameof(state));

        var root = new XElement(Ns + "pyexcel",
            new XAttribute("state-version", SchemaVersion),
            new XElement(Ns + "enabled", XmlConvert.ToString(state.Enabled)));

        if (state.SelectedScript is not null)
            root.Add(new XElement(Ns + "selected-script", state.SelectedScript));
        if (state.PyInput is not null)
            root.Add(new XElement(Ns + "py-input", state.PyInput));
        if (state.PyOutput is not null)
            root.Add(new XElement(Ns + "py-output", state.PyOutput));
        if (state.SelectedActionName is not null)
            root.Add(new XElement(Ns + "selected-action", state.SelectedActionName));

        var actions = new XElement(Ns + "actions");
        foreach (var a in state.Actions)
            actions.Add(SerializeAction(a));
        root.Add(actions);

        return new XDocument(new XDeclaration("1.0", "utf-8", null), root);
    }

    private static XElement SerializeAction(RibbonAction a)
    {
        var el = new XElement(Ns + "action",
            new XAttribute("name", a.Name),
            new XAttribute("script", a.Script),
            new XAttribute("input", a.Input),
            new XAttribute("output", a.Output));

        if (a.Kwargs is { Count: > 0 })
        {
            var kwargs = new XElement(Ns + "kwargs");
            // Stable ordering — keeps the on-disk format deterministic so
            // a no-op save doesn't churn the workbook's binary diff.
            foreach (var kv in a.Kwargs.OrderBy(p => p.Key, StringComparer.Ordinal))
            {
                kwargs.Add(new XElement(Ns + "kwarg",
                    new XAttribute("key", kv.Key),
                    new XAttribute("value", kv.Value)));
            }
            el.Add(kwargs);
        }

        return el;
    }

    /// <summary>Deserialize a document produced by
    /// <see cref="Serialize"/> into a fresh <see cref="WorkbookState"/>
    /// keyed by <paramref name="workbookKey"/>. Transient fields
    /// (<see cref="WorkbookState.CurrentSheet"/>,
    /// <see cref="WorkbookState.AvailableScripts"/>) are left at their
    /// defaults; the caller is responsible for repopulating them from
    /// live sources.</summary>
    /// <exception cref="FormatException">The document isn't a recognised
    /// PyExcel state document (wrong root, wrong namespace,
    /// unsupported schema version).</exception>
    public static WorkbookState Deserialize(XDocument document, string workbookKey)
    {
        if (document is null) throw new ArgumentNullException(nameof(document));
        if (workbookKey is null) throw new ArgumentNullException(nameof(workbookKey));

        var root = document.Root
            ?? throw new FormatException("document has no root element");
        if (root.Name != Ns + "pyexcel")
            throw new FormatException(
                $"unexpected root element '{root.Name}' (expected '{{{XmlNamespace}}}pyexcel')");

        var version = (string?)root.Attribute("state-version");
        if (version != SchemaVersion)
            throw new FormatException(
                $"unsupported state-version '{version}' (this build expects '{SchemaVersion}')");

        var enabled = ParseBool(root.Element(Ns + "enabled")?.Value);
        var selectedScript = (string?)root.Element(Ns + "selected-script");
        var pyInput = (string?)root.Element(Ns + "py-input");
        var pyOutput = (string?)root.Element(Ns + "py-output");
        var selectedAction = (string?)root.Element(Ns + "selected-action");

        var actions = new List<RibbonAction>();
        var actionsEl = root.Element(Ns + "actions");
        if (actionsEl is not null)
        {
            foreach (var a in actionsEl.Elements(Ns + "action"))
                actions.Add(DeserializeAction(a));
        }

        return WorkbookState.Empty(workbookKey) with
        {
            Enabled = enabled,
            SelectedScript = selectedScript,
            PyInput = pyInput,
            PyOutput = pyOutput,
            Actions = actions,
            SelectedActionName = selectedAction,
        };
    }

    private static RibbonAction DeserializeAction(XElement el)
    {
        var name = RequireAttribute(el, "name");
        var script = RequireAttribute(el, "script");
        var input = RequireAttribute(el, "input");
        var output = RequireAttribute(el, "output");

        Dictionary<string, string>? kwargs = null;
        var kwargsEl = el.Element(Ns + "kwargs");
        if (kwargsEl is not null)
        {
            kwargs = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (var kv in kwargsEl.Elements(Ns + "kwarg"))
            {
                var key = RequireAttribute(kv, "key");
                var value = RequireAttribute(kv, "value");
                kwargs[key] = value;
            }
        }

        return new RibbonAction(name, script, input, output, kwargs);
    }

    private static string RequireAttribute(XElement el, string name)
    {
        var attr = el.Attribute(name);
        if (attr is null)
            throw new FormatException(
                $"element '{el.Name.LocalName}' is missing required attribute '{name}'");
        return attr.Value;
    }

    private static bool ParseBool(string? value)
    {
        if (value is null)
            throw new FormatException("missing <enabled> element");
        // XmlConvert handles "true"/"false"/"1"/"0" per XML spec.
        try { return XmlConvert.ToBoolean(value.Trim().ToLowerInvariant()); }
        catch (FormatException ex)
        {
            throw new FormatException(
                $"invalid <enabled> value '{value}'", ex);
        }
    }
}
