using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Xml;
using System.Xml.Linq;

namespace PyExcel.State;

/// <summary>
/// Pure-XML round-trip for the user-editable slice of
/// <see cref="WorkbookState"/>. Used by the Phase-3
/// <c>WorkbookStatePersister</c> (Windows-only, COM-bound) to save into
/// and load out of a workbook's <c>CustomXMLPart</c> collection, but the
/// codec itself has no COM dependency so it builds and tests on Linux.
///
/// <para>The XML schema is intentionally hand-rolled, human-readable, and
/// versioned. The root element carries
/// <c>xmlns="urn:pyexcel:state:1"</c> so the COM-side persister can
/// locate the part among any other CustomXMLParts the workbook owns.
/// Bumping the schema means bumping the namespace.</para>
///
/// <para>What's persisted: the user-input fields
/// (<see cref="WorkbookState.Enabled"/>, <see cref="WorkbookState.SelectedScript"/>,
/// <see cref="WorkbookState.PyInput"/>, <see cref="WorkbookState.PyOutput"/>,
/// <see cref="WorkbookState.SelectedActionName"/>, and the full
/// <see cref="WorkbookState.Actions"/> list).
/// What's NOT persisted: <see cref="WorkbookState.WorkbookKey"/> (it's
/// the lookup key, not data),
/// <see cref="WorkbookState.CurrentSheet"/> (transient — derived from
/// <c>SheetActivate</c>), <see cref="WorkbookState.AvailableScripts"/>
/// (regenerated by <see cref="ScriptDirectoryWatcher"/> on workbook
/// open).</para>
/// </summary>
public static class WorkbookStateCodec
{
    /// <summary>Current schema version. Bump when the on-disk format
    /// changes in a non-backwards-compatible way.</summary>
    public const string SchemaVersion = "1";

    /// <summary>XML namespace embedded in the root element so the COM
    /// persister can find the PyExcel part among other custom parts.
    /// Reads accept only this exact namespace — see
    /// <see cref="Deserialize"/>.</summary>
    public const string XmlNamespace = "urn:pyexcel:state:1";

    private static readonly XNamespace Ns = XmlNamespace;

    /// <summary>Serialize the user-editable slice of
    /// <paramref name="state"/> into an XML document the persister can
    /// store in a <c>CustomXMLPart</c>.</summary>
    public static XDocument Serialize(WorkbookState state)
    {
        if (state is null) throw new ArgumentNullException(nameof(state));

        var root = new XElement(Ns + "pyexcel",
            new XAttribute("state-version", SchemaVersion),
            new XElement(Ns + "enabled", XmlConvert.ToString(state.Enabled)));

        if (state.SelectedScript is not null)
            root.Add(new XElement(Ns + "selected-script", state.SelectedScript));
        if (state.PyInput is not null)
            root.Add(new XElement(Ns + "py-input", state.PyInput));
        if (state.PyOutput is not null)
            root.Add(new XElement(Ns + "py-output", state.PyOutput));
        if (state.SelectedActionName is not null)
            root.Add(new XElement(Ns + "selected-action", state.SelectedActionName));
        // Phase 5 — Import / Export / Paste text fields. Schema stays at
        // version 1: the new elements are optional, so a document written
        // before this change still parses (missing → null), and a document
        // written after still satisfies the v1 namespace contract for any
        // reader that doesn't know about them.
        if (state.ImportInput is not null)
            root.Add(new XElement(Ns + "import-input", state.ImportInput));
        if (state.ImportOutput is not null)
            root.Add(new XElement(Ns + "import-output", state.ImportOutput));
        if (state.ExportInput is not null)
            root.Add(new XElement(Ns + "export-input", state.ExportInput));
        if (state.ExportOutput is not null)
            root.Add(new XElement(Ns + "export-output", state.ExportOutput));
        // Structured export defaults (folder / base name / file type / unique-name
        // stamp). Optional like every field above, so a document written before
        // they existed parses with each one null.
        if (state.ExportFolder is not null)
            root.Add(new XElement(Ns + "export-folder", state.ExportFolder));
        if (state.ExportBaseName is not null)
            root.Add(new XElement(Ns + "export-base-name", state.ExportBaseName));
        if (state.ExportFormat is not null)
            root.Add(new XElement(Ns + "export-format", state.ExportFormat));
        if (state.ExportTimestamp is not null)
            root.Add(new XElement(Ns + "export-timestamp", state.ExportTimestamp));
        if (state.PasteOutput is not null)
            root.Add(new XElement(Ns + "paste-output", state.PasteOutput));
        // The user-chosen dedicated project directory (Enable). Optional, so a
        // document written before this change parses with ProjectDir == null.
        if (state.ProjectDir is not null)
            root.Add(new XElement(Ns + "project-dir", state.ProjectDir));

        var actions = new XElement(Ns + "actions");
        foreach (var a in state.Actions)
            actions.Add(SerializeAction(a));
        root.Add(actions);

        return new XDocument(new XDeclaration("1.0", "utf-8", null), root);
    }

    /// <summary>Serialize <paramref name="state"/> to a compact XML string
    /// suitable for storing in a workbook's <c>CustomXMLPart</c>. The root
    /// element carries <see cref="XmlNamespace"/> so the COM-side persister
    /// can locate the part again via <c>SelectByNamespace</c>; formatting is
    /// disabled so the on-disk bytes stay deterministic across no-op saves.</summary>
    public static string SerializeToString(WorkbookState state)
        => Serialize(state).ToString(SaveOptions.DisableFormatting);

    private static XElement SerializeAction(RibbonAction a)
    {
        var el = new XElement(Ns + "action",
            new XAttribute("name", a.Name),
            new XAttribute("script", a.Script),
            new XAttribute("input", a.Input),
            new XAttribute("output", a.Output));

        // Optional, written only when it differs from the default (true), so an
        // unchanged action serialises byte-identically and a no-op save doesn't
        // churn the part. Absent on read → true (see DeserializeAction).
        if (!a.KeepOutputOpen)
            el.Add(new XAttribute("keep-output-open", XmlConvert.ToString(false)));

        if (a.Kwargs is { Count: > 0 })
        {
            var kwargs = new XElement(Ns + "kwargs");
            // Stable ordering — keeps the on-disk format deterministic so
            // a no-op save doesn't churn the workbook's binary diff.
            foreach (var kv in a.Kwargs.OrderBy(p => p.Key, StringComparer.Ordinal))
            {
                kwargs.Add(new XElement(Ns + "kwarg",
                    new XAttribute("key", kv.Key),
                    new XAttribute("value", kv.Value)));
            }
            el.Add(kwargs);
        }

        return el;
    }

    /// <summary>Deserialize a document produced by
    /// <see cref="Serialize"/> into a fresh <see cref="WorkbookState"/>
    /// keyed by <paramref name="workbookKey"/>. Transient fields
    /// (<see cref="WorkbookState.CurrentSheet"/>,
    /// <see cref="WorkbookState.AvailableScripts"/>) are left at their
    /// defaults; the caller is responsible for repopulating them from
    /// live sources.</summary>
    /// <exception cref="FormatException">The document isn't a recognised
    /// PyExcel state document (wrong root, wrong namespace,
    /// unsupported schema version).</exception>
    public static WorkbookState Deserialize(XDocument document, string workbookKey)
    {
        if (document is null) throw new ArgumentNullException(nameof(document));
        if (workbookKey is null) throw new ArgumentNullException(nameof(workbookKey));

        var root = document.Root
            ?? throw new FormatException("document has no root element");
        if (root.Name != Ns + "pyexcel")
            throw new FormatException(
                $"unexpected root element '{root.Name}' (expected '{{{XmlNamespace}}}pyexcel')");

        var version = (string?)root.Attribute("state-version");
        if (version != SchemaVersion)
            throw new FormatException(
                $"unsupported state-version '{version}' (this build expects '{SchemaVersion}')");

        var enabled = ParseBool(root.Element(Ns + "enabled")?.Value);
        var selectedScript = (string?)root.Element(Ns + "selected-script");
        var pyInput = (string?)root.Element(Ns + "py-input");
        var pyOutput = (string?)root.Element(Ns + "py-output");
        var selectedAction = (string?)root.Element(Ns + "selected-action");
        // Phase 5 fields — optional, default to null on a document that
        // pre-dates them.
        var importInput = (string?)root.Element(Ns + "import-input");
        var importOutput = (string?)root.Element(Ns + "import-output");
        var exportInput = (string?)root.Element(Ns + "export-input");
        var exportOutput = (string?)root.Element(Ns + "export-output");
        var exportFolder = (string?)root.Element(Ns + "export-folder");
        var exportBaseName = (string?)root.Element(Ns + "export-base-name");
        var exportFormat = (string?)root.Element(Ns + "export-format");
        var exportTimestamp = (string?)root.Element(Ns + "export-timestamp");
        var pasteOutput = (string?)root.Element(Ns + "paste-output");
        var projectDir = (string?)root.Element(Ns + "project-dir");

        var actions = new List<RibbonAction>();
        var actionsEl = root.Element(Ns + "actions");
        if (actionsEl is not null)
        {
            foreach (var a in actionsEl.Elements(Ns + "action"))
                actions.Add(DeserializeAction(a));
        }

        return WorkbookState.Empty(workbookKey) with
        {
            Enabled = enabled,
            SelectedScript = selectedScript,
            PyInput = pyInput,
            PyOutput = pyOutput,
            Actions = actions,
            SelectedActionName = selectedAction,
            ImportInput = importInput,
            ImportOutput = importOutput,
            ExportInput = exportInput,
            ExportOutput = exportOutput,
            ExportFolder = exportFolder,
            ExportBaseName = exportBaseName,
            ExportFormat = exportFormat,
            ExportTimestamp = exportTimestamp,
            PasteOutput = pasteOutput,
            ProjectDir = projectDir,
        };
    }

    /// <summary>Best-effort parse of a <c>CustomXMLPart</c>'s XML back into
    /// a <see cref="WorkbookState"/> keyed by <paramref name="workbookKey"/>.
    /// Returns <see langword="false"/> (with a null
    /// <paramref name="state"/>) for null/blank input, non-XML, or any
    /// document that isn't a recognised PyExcel state part (wrong root,
    /// namespace, or schema version) — so a corrupt or foreign part can
    /// never throw into the COM event handler that calls this. Genuine
    /// parse successes still go through <see cref="Deserialize"/>, so the
    /// caller-supplied key wins over anything that might be in the XML.</summary>
    public static bool TryDeserialize(string? xml, string workbookKey, out WorkbookState? state)
    {
        if (workbookKey is null) throw new ArgumentNullException(nameof(workbookKey));
        state = null;
        if (string.IsNullOrWhiteSpace(xml)) return false;
        try
        {
            var doc = XDocument.Parse(xml);
            state = Deserialize(doc, workbookKey);
            return true;
        }
        catch (Exception ex) when (ex is FormatException or XmlException)
        {
            // Foreign / corrupt / wrong-version part — not ours to read.
            return false;
        }
    }

    private static RibbonAction DeserializeAction(XElement el)
    {
        var name = RequireAttribute(el, "name");
        var script = RequireAttribute(el, "script");
        var input = RequireAttribute(el, "input");
        var output = RequireAttribute(el, "output");

        Dictionary<string, string>? kwargs = null;
        var kwargsEl = el.Element(Ns + "kwargs");
        if (kwargsEl is not null)
        {
            kwargs = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (var kv in kwargsEl.Elements(Ns + "kwarg"))
            {
                var key = RequireAttribute(kv, "key");
                var value = RequireAttribute(kv, "value");
                kwargs[key] = value;
            }
        }

        return new RibbonAction(
            name, script, input, output, kwargs, ParseKeepOutputOpen(el));
    }

    /// <summary>Read an action's optional <c>keep-output-open</c> attribute,
    /// defaulting to <see langword="true"/> when absent (a part written before
    /// this field existed) or malformed — so the toggle never breaks a load.</summary>
    private static bool ParseKeepOutputOpen(XElement el)
    {
        var attr = el.Attribute("keep-output-open");
        if (attr is null) return true;
        try { return XmlConvert.ToBoolean(attr.Value.Trim().ToLowerInvariant()); }
        catch (FormatException) { return true; }
    }

    private static string RequireAttribute(XElement el, string name)
    {
        var attr = el.Attribute(name);
        if (attr is null)
            throw new FormatException(
                $"element '{el.Name.LocalName}' is missing required attribute '{name}'");
        return attr.Value;
    }

    private static bool ParseBool(string? value)
    {
        if (value is null)
            throw new FormatException("missing <enabled> element");
        // XmlConvert handles "true"/"false"/"1"/"0" per XML spec.
        try { return XmlConvert.ToBoolean(value.Trim().ToLowerInvariant()); }
        catch (FormatException ex)
        {
            throw new FormatException(
                $"invalid <enabled> value '{value}'", ex);
        }
    }
}
